# Generated by Django 5.1.6 on 2025-02-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=255)),
                ('instrucoes', models.TextField()),
                ('frequencia', models.CharField(choices=[('DI', 'Diariamente'), ('1X', '1x por semana'), ('2X', '2x por semana'), ('3X', '3x por semana'), ('4X', '4x por semana'), ('SN', 'Somente quando necessário')], default='DI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor', models.PositiveIntegerField()),
                ('registro_geral', models.TextField()),
                ('video', models.FileField(upload_to='video')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes')),
                ('tarefas', models.ManyToManyField(to='pacientes.tarefas')),
            ],
        ),
    ]
